## LANGUAGE
defaultContentLanguage: fr

## ADVANCED
build:
  buildStats:
    disableClasses: false
    disableIDs: true
    disableTags: false
    enable: true
enableRobotsTXT: true
imaging:
  anchor: Smart
  hint: picture
  quality: 75
  resampleFilter: Lanczos
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 9
removePathAccents: true
timeout: 100000
