## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  anchor: Smart
  hint: picture
  quality: 85
  resampleFilter: Lanczos
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 9
removePathAccents: true
disableHugoGeneratorInject: true
timeout: 100000
