_merge: deep

# Images
logo:
  header: false
  footer: /assets/images/logo-footer.svg
hero:
  cover: 1600x350
  cover_mobile: 375x200
image:
  retina:
    desktop: true

# Javascripts
animation: false
carousel: true
map: true
parallax: 
  enable: false
bootstrap:
  carousel: false 
  collapse: false 
  dropdown: true 
  modal: false 
  offcanvas: true 
  popover: false 
  scrollspy: false 
  tab: false 
  toast: false
  tooltip: false 

# CMS
admin:

  # Config
  i18n:
    default_locale: fr
    locales: '[fr,en,es]'
  config:
    id: false

  # Collections
  collections:
    config:
      files:
        - nav-primary
        - nav-secondary
        - booking
        - nav-legal
        - nav-social
        - banner
        - footer
        - seo
    indexes:
      enable: false
    pages:
      fields:
        - is_page
        - draft
        - title_page
        - description
        - featured_image
        - hero
        - blocks
        - body
        - slug
  
  # Blocks
  blocks:
    enable:
      - alert
      - editorial
      - form
      - figure
      - gallery
      - informations
      - map
      - pushes
      - table
      - testimonials
      - title

  # Shortcodes
  shortcodes:
    enable:
      - blank_link